# Generated by Django 3.1 on 2020-11-14 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='members',
        ),
        migrations.RemoveField(
            model_name='user',
            name='organizations',
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='expenses.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='location_id',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='OrganizationMember',
        ),
    ]
