# Generated by Django 3.1 on 2020-11-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_auto_20201116_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='users',
            new_name='members',
        ),
        migrations.AlterField(
            model_name='user',
            name='organizations',
            field=models.ManyToManyField(through='expenses.OrganizationMember', to='expenses.Organization'),
        ),
    ]
