# Generated by Django 3.1 on 2020-11-17 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_auto_20201116_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymember',
            name='organization',
        ),
        migrations.AddField(
            model_name='category',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='expenses.organization'),
            preserve_default=False,
        ),
    ]
