# Generated by Django 3.1 on 2020-11-17 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_auto_20201117_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='organization',
        ),
    ]
