# Generated by Django 3.1 on 2020-11-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_remove_expense_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationmember',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='expense_limit',
            field=models.IntegerField(default=10000),
            preserve_default=False,
        ),
    ]
