# Generated by Django 3.1 on 2020-11-19 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_auto_20201119_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='expense_limit',
        ),
    ]
